[package]
name = "shepards"
version = "0.1.0"
authors = ["tourtiere <https://github.com/tourtiere>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"
